### ISSUE TITLE
HandleError

### ISSUE THREAD

**Issue by herlon214** [fabiocicerchia/salmonjs#55]
I tried to use the salmon js but gave me an error:

``` javascript
.-----.---.-.|  |.--------.-----.-----._|     |     __|
|__ --|  _  ||  ||        |  _  |     |       |__     |
|_____|___._||__||__|__|__|_____|__|__|_______|_______|

salmonJS v0.5.0
Copyright (C) 2014 Fabio Cicerchia <info@fabiocicerchia.it>

2014-11-20T17:34:22.973Z - info:    Report anonymous statistics: Yes
2014-11-20T17:34:22.975Z - info:    Start processing "http://www.ofertasdeemail.com.br/"...
2014-11-20T17:34:23.085Z - info:    Started new crawler: 17572
2014-11-20T17:34:24.088Z - info:    [db6115dc-17572] Launching crawler to parse "http://www.ofertasdeemail.com.br/" - N/A on N/A ...
2014-11-20T17:34:24.095Z - error:   undefined

/usr/local/lib/node_modules/salmonjs/src/crawler.js:286
                this.handleError();
                     ^
TypeError: Object #<ChildProcess> has no method 'handleError'
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/salmonjs/src/crawler.js:286:22)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:808:12)


```

**Comment by t3db0t** [comment]
I was just getting this. I fixed it by—I THINK—upgrading PhantomJS. do `brew upgrade phantomjs` or `brew install phantomjs` if you don't have it already

**Comment by herlon214** [comment]
I didn't use this anymore, but thanks for the feedback @t3db0t :ok_hand:
